### ISSUE TITLE
--config is not recognized

### ISSUE THREAD

**Issue by jamesmortensen** [rdio/jsfmt#107]
When trying to pass in the configuration, as specified [in the docs](https://github.com/rdio/jsfmt#jsfmtrc), I get the following error message on the terminal:

```
$ jsfmt --config config.json
--config is not recognized
```

I tried with and without specifying a file.  It would appear the --config flag is not recognized.  Hope this  helps.

**Comment by feross** [comment]
I need the `--config` option to build an auto-formatter for [`standard`](https://github.com/feross/standard). I need to invoke `jsfmt` with a custom `.jsfmtrc` that exists inside the `standard` module, not in the user's home or project directory.

Can this option be re-added?
