### ISSUE TITLE
arguments with multiple objects are being formatted oddly

### ISSUE THREAD

**Issue by jonathanong** [rdio/jsfmt#120]
looks like this:

```js
fn({
  a: 1
}, {
    b: 2
  })
```

**Comment by millermedeiros** [comment]
the CallExpression was actually fixed this week on esformatter: https://github.com/millermedeiros/esformatter/issues/238 - I should release a new version next week containing the fix (just trying to solve a couple other bugs as well before doing the release)

**Comment by jimfleming** [comment]
#135
