### ISSUE TITLE
JSX support

### ISSUE THREAD

**Issue by pjvds** [rdio/jsfmt#124]
Are there any plans to support the formatting of JSX files as well?

**Comment by arypurnomoz** [comment]
+1

**Comment by JustinTulloss** [comment]
It might be relatively simple if we use facebook's for of esprima that supports JSX already. https://github.com/facebook/esprima

**Comment by jimfleming** [comment]
@JustinTulloss Yup, it would also fix some of #122 as well.

**Comment by seandunn** [comment]
Looks like Facebook branch also supports type annotations for Flow. ...which is nice.

**Comment by danawoodman** [comment]
Any updates on this? The lack of JSX support is really unfortunate.

**Comment by dahjelle** [comment]
It appears that you can use `esformatter` plugins for `jsfmt`, and the [`esformatter-jsx`](https://www.npmjs.com/package/esformatter-jsx) plugin offers at least rudimentary JSX support.

**Comment by royriojas** [comment]
Yes, the plugin is actually very simple, but it worked fine on several relative complex jsx structures. 

Here is a live demo, just in case http://requirebin.com/embed?gist=0d67452e01754269660f

**Comment by koorgoo** [comment]
+1

**Comment by Rudolph-Miller** [comment]
+1

**Comment by yanqirenshi** [comment]
+1

**Comment by axyz** [comment]
+1

**Comment by jeffreylo** [comment]
+1

**Comment by royriojas** [comment]
This guide might help to setup esformatter-jsx with jsfmt

https://github.com/royriojas/esformatter-jsx/wiki/Usage-with-jsfmt

**Comment by brettlangdon** [comment]
Going to close this as we have merged in #178 which documents how to use the `esformatter-jsx` plugin with `jsfmt`.
