### ISSUE TITLE
Problem with object expression containing getters and setters

### ISSUE THREAD

**Issue by andrelillvede** [rdio/jsfmt#128]
When running `jsfmt -v test.js` where test.js contains:

    var o = {
	    a: 0,
	    get b() {}, 
	    set c(x) {}
    };

I get no error, but with:

    var o = {
	    get b() {}, 
	    set c(x) {}
    };

I get `test.js [TypeError: Cannot read property 'value' of undefined]`

and with: 

    var o = {
	    get b() {}, 
    };

I get `test.js [TypeError: Cannot read property 'root' of undefined]`

**Comment by millermedeiros** [comment]
FYI this was fixed on esformatter last week, we should release a new version soon.

**Comment by jimfleming** [comment]
Yah, we should update jsfmt to use the latest esformatter. I'll look into doing this as soon as I can.

**Comment by millermedeiros** [comment]
[esformatter v0.5.0](https://www.npmjs.com/package/esformatter) released today! fixed A LOT of bugs. please let me know if you guys find anything wrong/broken/missing so that I can fix it. reduced test cases are extremely useful.

**Comment by jimfleming** [comment]
@jish updated jsfmt to use esformatter v0.5.0 — will be publishing this update to npm today.

**Comment by jimfleming** [comment]
This should be pushed to npm now.
