### ISSUE TITLE
Format with extra newline

### ISSUE THREAD

**Issue by CatTail** [rdio/jsfmt#130]
Example javascript file `test.js`

```javascript
var a = 0;
```

when I invoke it with `jsfmt test.js`, the result is

```javascript
var a = 0;


```

With extra newline at the end of file.

**Comment by millermedeiros** [comment]
on esformatter we had the same problem, we solved by using `process.stdout.write` instead of a simple `console.log`

**Comment by jimfleming** [comment]
A fix #134 for this was merged in last week thanks to aredridel.
