### ISSUE TITLE
User config only extends plugins instead of overwriting

### ISSUE THREAD

**Issue by hoschi** [rdio/jsfmt#141]
Starting with version 0.4.1 my variable declarations are splitted by jsfmt. I think this is an issue because in the [esformatter preview](http://lloiser.github.io/esformatter-visualize/) it doesn't do this. Example

```
var a, b;
```
gets formatted to:
```
var a;
var b;
```

Config is here https://github.com/hoschi/sweetp-service-project-workflow/blob/develop/.jsfmtrc
Also you can test it in this repository by running `jsfmt -w test`.

**Comment by jimfleming** [comment]
This is intentional per this PR: #125

You should be able to disable the plugin by overwriting the default plugins in your config:

```json
"plugins": ["esformatter-braces", "esformatter-var-each"]
```

If overwriting the plugin doesn't work, please re-open.

**Comment by brettlangdon** [comment]
@jimfleming the best thing I have here is `disablePlugins: ["esformatter-var"]` for the config.

It seems like an appropriate fix, but seems weird since we only have 2 plugins enabled.

Thoughts?

**Comment by brettlangdon** [comment]
I added a PR for that idea, it was easy enough to implement. I'm content if we decide not to merge it.

**Comment by brettlangdon** [comment]
@hoschi I could not reproduce this issue on `v0.4.1` using your example script and config.

**Comment by hoschi** [comment]
@brettlangdon strange, I try to test this again at the weekend and see what happens ;)

**Comment by hoschi** [comment]
@brettlangdon you are right I tested it again and it works with the posted config (not using `disablePlugins`)

**Comment by brettlangdon** [comment]
@hoschi awesome!
