### ISSUE TITLE
Add support for 'for (var x OF y)' syntax.

### ISSUE THREAD

**Issue by radare** [rdio/jsfmt#143]
Currently, v8 and gecko supports this syntax, but jsfmt is only able to parse the old es5 one. Adding support for this one is easy and will be good.

**Comment by jimfleming** [comment]
Updating to Esprima 2.0 might help here.

**Comment by jimfleming** [comment]
This might work with the Esprima update but we should add a test to verify.

**Comment by jimfleming** [comment]
This is now working.
