### ISSUE TITLE
.formatJSON add a new line at the end of the output

### ISSUE THREAD

**Issue by ionutvmi** [rdio/jsfmt#144]
If the input ends with a new line after the formatting the output will contain an extra new line.
Here is some code to reproduce the problem

```js
var jsfmt = require('jsfmt');
var fs = require('fs');

var input = '{"a":1,"b":"c"}\n';

var json = jsfmt.formatJSON(input);

fs.writeFile('test.txt', json);

```

jsfmt version: 0.4.1
node version: 0.10.31
This problem was not present in 0.4.0

**Comment by jimfleming** [comment]
Hmm, I thought we had a test to fix this. Will check it out.
