### ISSUE TITLE
Is jsfmt alive?

### ISSUE THREAD

**Issue by abdullin** [rdio/jsfmt#148]
There hasn't been any activity on Jsfmt repository in a while. Latest issues don't have any comments or replies on them.

Is this project alive, if I may ask?

**Comment by jimfleming** [comment]
I haven't had the time to maintain it since my day-to-day hasn't been in much JavaScript lately. Though the most recent issues should be quick fixes I don't seem to be on the repo as an admin anymore.

I'll see if I can work something out with access so PRs can still be merged.

**Comment by jimfleming** [comment]
Ok, permissions all sorted. I'll go through the PRs up there today and get it cleaned up. I still don't have much time to work on it, but PRs are welcome and I have some time to review them.

**Comment by abdullin** [comment]
Thank you for the update @jimfleming!
