### ISSUE TITLE
line break issue

### ISSUE THREAD

**Issue by jozecuervo** [rdio/jsfmt#149]
Yo dudes, just noticed an issue while un-minifying some google code. Here's the source:

http://www.gstatic.com/cast/sdk/libs/receiver/2.0.0/cast_receiver.js

Somewhere near the top of this file there's a `new` keyword with a line break (no spaces) and the constructor `c` on the next line. JSFMT cleans up the line break but does not preserve the separation  of the `new` keyword and the intended constructor `c`. I simply end up with `newc` and end up with very broken code. I'm assuming other google libraries will also use the same minification and therefore be mangled by jsfmt.

**Comment by brettlangdon** [comment]
@jozecuervo this issue appears to be resolved:

```js
...
      function c() {
      }
      c.prototype = b.prototype;
      a.D = b.prototype;
      a.prototype = new c;
      a.prototype.constructor = a;
...
```
