### ISSUE TITLE
Babel AST?

### ISSUE THREAD

**Issue by leeola** [rdio/jsfmt#150]
Would it be possible to use Babel AST to support a wider range of JS syntax and features? Not only ES6/ES7, but transforms that Babel supports - such as formatting FlowType _(but not the actual flow signatures)_

My current JS is all based around FlowType and Babel, so if there was some way to at least format FlowType code as plain JS, that would be amazing. 

I'm very unfamiliar with the requirements of AST parsing, so perhaps this is entirely not possible and way off base, but i don't see it discussed here so i figured it's worth bringing up.

Thanks,

**Comment by leeola** [comment]
Looks like esformatter has the same thought (https://github.com/millermedeiros/esformatter/issues/192#issuecomment-85652973). Given that jsfmt uses esformatter to process the source, i assume this is simply not possible here. This "issue" should probably be closed, but i'll leave it open for a bit to see if there's any additional discussion.

**Comment by jimfleming** [comment]
This would be awesome but, like you say, dependent on esformatter making the switch too.
