### ISSUE TITLE
Who is maintaining jsfmt?

### ISSUE THREAD

**Issue by brettlangdon** [rdio/jsfmt#154]
I know that @jimfleming is no longer at rdio and it seems like no one is maintaining this project anymore. Would love to get this figured out.

**Comment by dschleef** [comment]
@jimfleming has continued to maintain jsfmt after leaving Rdio, even though it's still under /rdio.  We  use it internally, so we're ok with that arrangement.  I assume that Jim is either taking a break from hacking or on vacation.  I'd like to defer to him for any official changes in maintainership, or more specifically, if he wants someone at Rdio to step up to merge pull requests when he's not around.

**Comment by brettlangdon** [comment]
Ok, great, awesome! Has just seemed a little quiet lately, wanted to make sure it wasn't getting forgotten.

**Comment by jimfleming** [comment]
Hi everyone! There have been a few permission issues with the jsfmt repo but we're working those out now so we should be able to resume normal operation shortly.

**Comment by jimfleming** [comment]
To answer the question: for now, myself and @brettlangdon. Permissions have been worked out and we can add others as it comes up.
