### ISSUE TITLE
Update version number

### ISSUE THREAD

**Issue by nederdirk** [rdio/jsfmt#159]
You recently merged to PRs of mine, but those are not yet in NPM, could you please update the version in NPM?

**Comment by jimfleming** [comment]
Yup, will do this today. Thanks for the reminder.

**Comment by jimfleming** [comment]
Currently `0.4.1`, will bump to `0.5.0` unless anyone has a suggestion for semver.

**Comment by jimfleming** [comment]
Pushed!
