### ISSUE TITLE
delete operator loses semicolon to newline

### ISSUE THREAD

**Issue by terinjokes** [rdio/jsfmt#165]
The "delete" operator loses it's semicolon to the next line

### input
```javascript
delete bag[item];
```

### output
```javascript
delete bag[item]
;
```

### expected
```javascript
delete bag[item];
```

**Comment by millermedeiros** [comment]
ops, esformatter fault. see https://github.com/millermedeiros/esformatter/issues/347

**Comment by brettlangdon** [comment]
@terinjokes this will be resolved in the next version of `jsfmt`

**Comment by terinjokes** [comment]
Perfect. Looking forward to the release.
