### ISSUE TITLE
Publish new version of jsfmt

### ISSUE THREAD

**Issue by brettlangdon** [rdio/jsfmt#168]
We have some new changes from #166 which we want to publish to npm.

Would we be able to bump version to `0.5.1` and publish to npm?

/cc @jimfleming

**Comment by jimfleming** [comment]
Sure thing. I can do this tomorrow.

**Comment by jimfleming** [comment]
Doing this now. Also updating our release tags since we're a few behind.

**Comment by brettlangdon** [comment]
Thanks @jimfleming

**Comment by jimfleming** [comment]
Cool, v0.5.1 is published both as a Github release: https://github.com/rdio/jsfmt/releases/tag/v0.5.1 and npm: https://www.npmjs.com/package/jsfmt
