### ISSUE TITLE
Release next version

### ISSUE THREAD

**Issue by brettlangdon** [rdio/jsfmt#172]
This PR is just a placeholder for releasing the next version of `jsfmt`. This way we can link pull requests for changes together in one place and get a good idea of when the next release should happen.

Included pull requests:
* #171 - Update Esprima to 2.7
* #173 - Run `jsfmt` on source code
* #174 - Run `jsfmt` + `diff` in test suite
* #176 - Update dependencies 
* #178 - Add docs about plugin usage
* #180 - Update esformatter

**Comment by jimfleming** [comment]
Nice, good idea.

**Comment by brettlangdon** [comment]
We are probably about due to release a new version.

**Comment by jimfleming** [comment]
Yup, I can take care of this today.

**Comment by jimfleming** [comment]
This is released: https://github.com/rdio/jsfmt/releases/tag/v0.5.2
