### ISSUE TITLE
TypeError processing for...of with variable declaration

### ISSUE THREAD

**Issue by ongardie** [rdio/jsfmt#181]
Here's an example:
```
$ cat test.js
"use strict";
let x = [4, 3, 2];
for (var v of x) {
  console.log(v);
}
$ node test.js 
4
3
2
$ node ./node_modules/jsfmt/bin/jsfmt test.js
test.js [TypeError: varDeclarationParentBody.indexOf is not a function]
$ node ./node_modules/jsfmt/bin/jsfmt --version
jsfmt 0.5.2
```

**Comment by brettlangdon** [comment]
@ongardie thank you for reporting!

Fun hint, you can do just `./node_modules/.bin/jsfmt`.

Yeah, there are some ES6 features which are not fully supported by `esformatter` or `esprima`, which is what we are using for parsing/formatting of code in `jsfmt`.

I started to compile a list of working ES6 examples and code which is not yet supported in #175, need to try and finish that at some point.

**Comment by ongardie** [comment]
@brettlangdon: ah, feel free to close if this is a duplicate of #175.

BTW, I've actually had pretty good luck with ES6 features so far. This is the first snag I've run into, and it's not a major one.
