### ISSUE TITLE
Strange behavior when rewriting commas

### ISSUE THREAD

**Issue by vangamo** [rdio/jsfmt#184]
I know I have so weird way to describe and comment my EcmaScript code, but I found this kind of error:

```
var obj = {
     "variable1": 1   // default value: 1
    ,"variable2": 2   // default value: 2
    ,"variable3": 3   // default value: 3

/**

  method1()  It does nothing

*/
    ,"method1": function() {

        }  // END method1()

/**

  method2()  Also, it does nothing

*/
    ,"method2": function() {

        }  // END method2()

    };  // END obj
```

This piece of code is formatted (or rewriten) into this:

```
var obj = {
  "variable1": 1, // default value: 1
  "variable2": 2, // default value: 2
  "variable3": 3, // default value: 3 /**

  method1()  It does nothing

*/
  "method1": function() {}, // END method1() /**

  method2()  Also, it does nothing

*/
  "method2": function() {} // END method2()

};
// END obj
```

I don't really want you fix it but I'm so intrigued where is the problem.

**Comment by brettlangdon** [comment]
Hey @vangamo the problem is that it is rewriting the start to the multiline comments on the same line as a single line comment:

``` js
"variable3": 3, // single line comment /**

Multiline comment block

**/
```

What happens is that JavaScript thinks that `/**` is part of the single line comment, and therefore does not consider it as the start to the multiline block comment.

Is this what you were looking for as an answer?

**Comment by vangamo** [comment]
I've detected that esformatter changes the code. I've submit an issue at its GitHub:
https://github.com/millermedeiros/esformatter/issues/407

**Comment by brettlangdon** [comment]
:+1:

We can leave this issue open until millermedeiros/esformatter#407 gets resolved.

**Comment by vangamo** [comment]
Hi!
Since I commented the lines suggested by Miller at https://github.com/millermedeiros/esformatter/issues/407#issuecomment-183829222 into esFormatter module (inside jsFmt) I don't get my js files corrupted.
I don't think this issue will become a real bug. It's only a single-particular-definite case.
Thank you very much!
