### ISSUE TITLE
Expose output and other configuration options via the API

### ISSUE THREAD

**Issue by jimfleming** [rdio/jsfmt#8]
> Also it seems like only rewrite and search are exposed via require. It would be nice to be able to pass an object for the output/config.

> Maybe something like jsfmt.rewrite(fileString, replaceRule, { list: false, comments: false })

> @james2doyle

**Comment by brettlangdon** [comment]
@jimfleming this has been open for a long time with no comments on it. Probably safe to close.

**Comment by jimfleming** [comment]
:+1:
